language: go

matrix:
  include:
  - go: "1.11.x"
    script:
      - go test -v -covermode=count -coverprofile=coverage.out ./...
      - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
  - go: "1.12.x"
    script:
      - go test -v -covermode=count -coverprofile=coverage.out ./...
      - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

install: true

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls
